language: ruby

sudo: false

rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "jruby-9.0.4.0"
  - "rbx-2.5.8"

script: rake test

cache: bundler

before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
